const colors = ['#6babac', '#e55253'];

const data = [
  { arg: 'Segunda', val: 25, parentID: '' },
  { arg: 'Terça', val: 37, parentID: '' },
  { arg: 'Quarta', val: 31, parentID: '' },
  { arg: 'Quinta', val: 14, parentID: '' },
  { arg: 'Sexta', val: 48, parentID: '' },
  { arg: '7h', val: 4, parentID: 'Quinta' },
  { arg: '10h', val: 5, parentID: 'Quinta' },
  { arg: '12h', val: 7, parentID: 'Quinta' },
  { arg: '18h', val: 8, parentID: 'Quinta' },
  { arg: '9h', val: 9, parentID: 'Segunda' },
  { arg: '10h', val: 10, parentID: 'Segunda' },
  { arg: '12h', val: 4, parentID: 'Segunda' },
  { arg: '18h', val: 5, parentID: 'Segunda' },
  { arg: '7h', val: 7, parentID: 'Quarta' },
  { arg: '8h', val: 3, parentID: 'Quarta' },
  { arg: '12h', val: 8, parentID: 'Quarta' },
  { arg: '15h', val: 11, parentID: 'Quarta' },
  { arg: '18h', val: 12, parentID: 'Quarta' },
  { arg: '7h', val: 4, parentID: 'Terça' },
  { arg: '12h', val: 7, parentID: 'Terça' },
  { arg: '17h', val: 8, parentID: 'Terça' },
  { arg: '18h', val: 5, parentID: 'Terça' },
  { arg: '7h', val: 2, parentID: 'Sexta' },
  { arg: '10h', val: 1, parentID: 'Sexta' },
  { arg: '12h', val: 3, parentID: 'Sexta' },
  { arg: '17h', val: 5, parentID: 'Sexta' },
  { arg: '18h', val: 4, parentID: 'Sexta' },
];
